services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    working_dir: /app
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
    command: ["npx","metro","serve","--host","0.0.0.0","--port","8081"]
