services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - appnet
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - appnet

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - "8080:8080"  # เปิด http://<host>:8080 แล้วเลือก System=PostgreSQL, Server=postgres
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
