import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    a1: {
        flex: 1,
        backgroundColor: "#FDF2E9",
    },
    a2: {
        flex: 1,
        backgroundColor: "#FDF2E9",
        padding: 20,
        marginTop: 70,
    },
    headerTitle: {
        fontSize: 26,
        fontWeight: "bold",
        color: "#E74C3C",
        textAlign: "center",
        marginVertical: 20,
    },
    contentContainer: {
        paddingHorizontal: 10,
    },
    addCourseButton: {
        backgroundColor: "#E74C3C",
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    addCourseButtonText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
    },
    courseCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 12,
        marginBottom: 20,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    courseImage: {
        width: 150,
        height: 150,
        borderRadius: 8,
        marginRight: 15,
        borderWidth: 1,
        borderColor: "#ddd",
    },
    courseDetails: {
        flex: 1,
    },
    courseTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 5,
    },
    coursePrice: {
        fontSize: 14,
        color: "#E74C3C",
        fontWeight: "bold",
        marginBottom: 5,
    },
    courseInstructor: {
        fontSize: 13,
        color: "#555",
        marginBottom: 5,
    },
    courseStatus: {
        fontSize: 14,
        fontWeight: "bold",
        marginBottom: 5,
    },
    revisionMessage: {
        fontSize: 14,
        color: "#D35400",
        fontWeight: "bold",
        marginTop: 5,
        backgroundColor: "#FAD7A0",
        padding: 5,
        borderRadius: 5,
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 10,
    },
    actionButtonContainer: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 8, 
        flexWrap: "wrap", 
    },
    editButton: {
        backgroundColor: "#3498DB",
        padding: 10,
        borderRadius: 5,
        flex: 1,
        alignItems: "center",
        maxWidth: "30%",
    },
    deleteButton: {
        backgroundColor: "#E74C3C",
        padding: 10,
        borderRadius: 5,
        flex: 1,
        alignItems: "center",
        maxWidth: "30%",
    },
    toggleButton: {
        backgroundColor: "#FFA500",
        padding: 10,
        borderRadius: 5,
        flex: 1,
        alignItems: "center",
        maxWidth: "30%",
    },
    buttonText: {
        color: "#fff",
        fontWeight: "bold",
    },
    loadingText: {
        textAlign: "center",
        fontSize: 16,
        color: "#888",
        marginTop: 20,
    },
    noDataText: {
        textAlign: "center",
        fontSize: 16,
        color: "#888",
        marginTop: 20,
    },
});

export default styles;
